package com.company.bean;

public class Departement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_department.id
     *
     * @mbg.generated Mon Nov 08 13:50:47 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_department.name
     *
     * @mbg.generated Mon Nov 08 13:50:47 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_department.id
     *
     * @return the value of tbl_department.id
     *
     * @mbg.generated Mon Nov 08 13:50:47 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_department.id
     *
     * @param id the value for tbl_department.id
     *
     * @mbg.generated Mon Nov 08 13:50:47 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_department.name
     *
     * @return the value of tbl_department.name
     *
     * @mbg.generated Mon Nov 08 13:50:47 CST 2021
     */
    public String getName() {
        return name;
    }
public Departement() {
	
}
    public Departement(Integer id, String name) {
		super();
		this.id = id;
		this.name = name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_department.name
     *
     * @param name the value for tbl_department.name
     *
     * @mbg.generated Mon Nov 08 13:50:47 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	@Override
	public String toString() {
		return "Departement [id=" + id + ", name=" + name + "]";
	}
}